version: '3.7'

services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    networks:
      - vue-network

networks:
  vue-network:
    driver: bridge
